# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sam\.qgis2\python\plugins\Figure_Builder\forms\ui_New_Project_dialog.ui'
#
# Created: Mon Jan 22 18:58:15 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Ui_New_ProjectDialogBase(object):
    def setupUi(self, Ui_New_ProjectDialogBase):
        Ui_New_ProjectDialogBase.setObjectName(_fromUtf8("Ui_New_ProjectDialogBase"))
        Ui_New_ProjectDialogBase.resize(1628, 780)
        self.Master_Buttons = QtGui.QDialogButtonBox(Ui_New_ProjectDialogBase)
        self.Master_Buttons.setGeometry(QtCore.QRect(1450, 740, 171, 32))
        self.Master_Buttons.setOrientation(QtCore.Qt.Horizontal)
        self.Master_Buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.Master_Buttons.setObjectName(_fromUtf8("Master_Buttons"))
        self.Figure_list_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Figure_list_CAPTION.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.Figure_list_CAPTION.setObjectName(_fromUtf8("Figure_list_CAPTION"))
        self.Layer_List_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Layer_List_CAPTION.setGeometry(QtCore.QRect(390, 40, 281, 16))
        self.Layer_List_CAPTION.setObjectName(_fromUtf8("Layer_List_CAPTION"))
        self.Figure_Control_Path_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Figure_Control_Path_CAPTION.setGeometry(QtCore.QRect(20, 0, 361, 16))
        self.Figure_Control_Path_CAPTION.setObjectName(_fromUtf8("Figure_Control_Path_CAPTION"))
        self.Control_Ref_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Control_Ref_Search_BUTTON.setGeometry(QtCore.QRect(310, 20, 71, 21))
        self.Control_Ref_Search_BUTTON.setObjectName(_fromUtf8("Control_Ref_Search_BUTTON"))
        self.Figure_Zoom_Centroid_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Figure_Zoom_Centroid_CAPTION.setGeometry(QtCore.QRect(800, 247, 281, 16))
        self.Figure_Zoom_Centroid_CAPTION.setObjectName(_fromUtf8("Figure_Zoom_Centroid_CAPTION"))
        self.Centroid_X_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Centroid_X_CAPTION.setGeometry(QtCore.QRect(800, 270, 121, 16))
        self.Centroid_X_CAPTION.setObjectName(_fromUtf8("Centroid_X_CAPTION"))
        self.Centroid_Y_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Centroid_Y_CAPTION.setGeometry(QtCore.QRect(950, 270, 121, 16))
        self.Centroid_Y_CAPTION.setObjectName(_fromUtf8("Centroid_Y_CAPTION"))
        self.Zoom_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Zoom_CAPTION.setGeometry(QtCore.QRect(800, 320, 261, 16))
        self.Zoom_CAPTION.setObjectName(_fromUtf8("Zoom_CAPTION"))
        self.Populate_View_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Populate_View_BUTTON.setGeometry(QtCore.QRect(910, 240, 151, 31))
        self.Populate_View_BUTTON.setObjectName(_fromUtf8("Populate_View_BUTTON"))
        self.Q001_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q001_CHECK.setGeometry(QtCore.QRect(20, 80, 91, 17))
        self.Q001_CHECK.setObjectName(_fromUtf8("Q001_CHECK"))
        self.Q005_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q005_CHECK.setGeometry(QtCore.QRect(20, 140, 91, 17))
        self.Q005_CHECK.setObjectName(_fromUtf8("Q005_CHECK"))
        self.Q002_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q002_CHECK.setGeometry(QtCore.QRect(20, 110, 91, 17))
        self.Q002_CHECK.setObjectName(_fromUtf8("Q002_CHECK"))
        self.Q010_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q010_CHECK.setGeometry(QtCore.QRect(20, 170, 91, 17))
        self.Q010_CHECK.setObjectName(_fromUtf8("Q010_CHECK"))
        self.Q100_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q100_CHECK.setGeometry(QtCore.QRect(20, 260, 91, 17))
        self.Q100_CHECK.setObjectName(_fromUtf8("Q100_CHECK"))
        self.Q200_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q200_CHECK.setGeometry(QtCore.QRect(20, 290, 91, 17))
        self.Q200_CHECK.setObjectName(_fromUtf8("Q200_CHECK"))
        self.Q020_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q020_CHECK.setGeometry(QtCore.QRect(20, 200, 91, 17))
        self.Q020_CHECK.setObjectName(_fromUtf8("Q020_CHECK"))
        self.Q050_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q050_CHECK.setGeometry(QtCore.QRect(20, 230, 91, 17))
        self.Q050_CHECK.setObjectName(_fromUtf8("Q050_CHECK"))
        self.Q2000_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q2000_CHECK.setGeometry(QtCore.QRect(20, 380, 91, 17))
        self.Q2000_CHECK.setObjectName(_fromUtf8("Q2000_CHECK"))
        self.QPMF_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.QPMF_CHECK.setGeometry(QtCore.QRect(20, 410, 70, 17))
        self.QPMF_CHECK.setObjectName(_fromUtf8("QPMF_CHECK"))
        self.Q500_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q500_CHECK.setGeometry(QtCore.QRect(20, 320, 91, 17))
        self.Q500_CHECK.setObjectName(_fromUtf8("Q500_CHECK"))
        self.Q1000_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Q1000_CHECK.setGeometry(QtCore.QRect(20, 350, 91, 17))
        self.Q1000_CHECK.setObjectName(_fromUtf8("Q1000_CHECK"))
        self.Event_Notation_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Event_Notation_CAPTION.setGeometry(QtCore.QRect(120, 50, 111, 16))
        self.Event_Notation_CAPTION.setObjectName(_fromUtf8("Event_Notation_CAPTION"))
        self.Mapping_Results_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Mapping_Results_CAPTION.setGeometry(QtCore.QRect(10, 440, 111, 16))
        self.Mapping_Results_CAPTION.setObjectName(_fromUtf8("Mapping_Results_CAPTION"))
        self.Res1_Location_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Res1_Location_CAPTION.setGeometry(QtCore.QRect(240, 440, 151, 16))
        self.Res1_Location_CAPTION.setObjectName(_fromUtf8("Res1_Location_CAPTION"))
        self.Velocity_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Velocity_CHECK.setGeometry(QtCore.QRect(10, 530, 91, 17))
        self.Velocity_CHECK.setObjectName(_fromUtf8("Velocity_CHECK"))
        self.Z0_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Z0_CHECK.setGeometry(QtCore.QRect(10, 560, 91, 17))
        self.Z0_CHECK.setObjectName(_fromUtf8("Z0_CHECK"))
        self.HydCat_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.HydCat_CHECK.setGeometry(QtCore.QRect(10, 620, 91, 17))
        self.HydCat_CHECK.setObjectName(_fromUtf8("HydCat_CHECK"))
        self.Level_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Level_CHECK.setGeometry(QtCore.QRect(10, 470, 91, 17))
        self.Level_CHECK.setObjectName(_fromUtf8("Level_CHECK"))
        self.Depth_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Depth_CHECK.setGeometry(QtCore.QRect(10, 500, 91, 17))
        self.Depth_CHECK.setObjectName(_fromUtf8("Depth_CHECK"))
        self.Risk_Precincts_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_CHECK.setGeometry(QtCore.QRect(10, 650, 91, 17))
        self.Risk_Precincts_CHECK.setObjectName(_fromUtf8("Risk_Precincts_CHECK"))
        self.Z1_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Z1_CHECK.setGeometry(QtCore.QRect(10, 590, 91, 17))
        self.Z1_CHECK.setObjectName(_fromUtf8("Z1_CHECK"))
        self.Res1_VCP_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Res1_VCP_CAPTION.setGeometry(QtCore.QRect(400, 440, 101, 16))
        self.Res1_VCP_CAPTION.setObjectName(_fromUtf8("Res1_VCP_CAPTION"))
        self.Level_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 470, 41, 21))
        self.Level_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Res1_Loc_Search_BUTTON"))
        self.Depth_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Depth_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 500, 41, 20))
        self.Depth_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Depth_Res1_Loc_Search_BUTTON"))
        self.Velocity_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 530, 41, 21))
        self.Velocity_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Res1_Loc_Search_BUTTON"))
        self.Z0_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z0_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 560, 41, 21))
        self.Z0_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z0_Res1_Loc_Search_BUTTON"))
        self.Z1_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z1_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 590, 41, 21))
        self.Z1_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z1_Res1_Loc_Search_BUTTON"))
        self.Risk_Precincts_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 650, 41, 21))
        self.Risk_Precincts_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Risk_Precincts_Res1_Loc_Search_BUTTON"))
        self.HydCat_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.HydCat_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 620, 41, 21))
        self.HydCat_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("HydCat_Res1_Loc_Search_BUTTON"))
        self.Scenario_Notation_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Scenario_Notation_CAPTION.setGeometry(QtCore.QRect(1000, 90, 171, 20))
        self.Scenario_Notation_CAPTION.setObjectName(_fromUtf8("Scenario_Notation_CAPTION"))
        self.Scenario_Title_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Scenario_Title_CAPTION.setGeometry(QtCore.QRect(800, 90, 191, 20))
        self.Scenario_Title_CAPTION.setObjectName(_fromUtf8("Scenario_Title_CAPTION"))
        self.Layout_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Layout_SELECT.setGeometry(QtCore.QRect(800, 60, 221, 22))
        self.Layout_SELECT.setObjectName(_fromUtf8("Layout_SELECT"))
        self.Layout_SELECT.addItem(_fromUtf8(""))
        self.Layout_SELECT.addItem(_fromUtf8(""))
        self.Layout_SELECT.addItem(_fromUtf8(""))
        self.Layout_SELECT.addItem(_fromUtf8(""))
        self.Page_Layout_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Page_Layout_CAPTION.setGeometry(QtCore.QRect(800, 40, 121, 16))
        self.Page_Layout_CAPTION.setObjectName(_fromUtf8("Page_Layout_CAPTION"))
        self.Level_Impact_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 680, 41, 21))
        self.Level_Impact_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Impact_Res1_Loc_Search_BUTTON"))
        self.Level_Impacts_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Level_Impacts_CHECK.setGeometry(QtCore.QRect(10, 680, 91, 17))
        self.Level_Impacts_CHECK.setObjectName(_fromUtf8("Level_Impacts_CHECK"))
        self.Velocity_Impacts_CHECK = QtGui.QCheckBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impacts_CHECK.setGeometry(QtCore.QRect(10, 710, 91, 17))
        self.Velocity_Impacts_CHECK.setObjectName(_fromUtf8("Velocity_Impacts_CHECK"))
        self.Velocity_Impact_Res1_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res1_Loc_Search_BUTTON.setGeometry(QtCore.QRect(350, 710, 41, 21))
        self.Velocity_Impact_Res1_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Impact_Res1_Loc_Search_BUTTON"))
        self.Level_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 470, 41, 21))
        self.Level_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Res2_Loc_Search_BUTTON"))
        self.Z1_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z1_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 590, 41, 21))
        self.Z1_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z1_Res2_Loc_Search_BUTTON"))
        self.Velocity_Impact_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 710, 41, 21))
        self.Velocity_Impact_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Impact_Res2_Loc_Search_BUTTON"))
        self.HydCat_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.HydCat_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 620, 41, 21))
        self.HydCat_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("HydCat_Res2_Loc_Search_BUTTON"))
        self.Depth_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Depth_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 500, 41, 21))
        self.Depth_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Depth_Res2_Loc_Search_BUTTON"))
        self.Z0_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z0_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 560, 41, 21))
        self.Z0_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z0_Res2_Loc_Search_BUTTON"))
        self.Level_Impact_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 680, 41, 21))
        self.Level_Impact_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Impact_Res2_Loc_Search_BUTTON"))
        self.Velocity_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 530, 41, 21))
        self.Velocity_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Res2_Loc_Search_BUTTON"))
        self.Risk_Precincts_Res2_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res2_Loc_Search_BUTTON.setGeometry(QtCore.QRect(700, 650, 41, 21))
        self.Risk_Precincts_Res2_Loc_Search_BUTTON.setObjectName(_fromUtf8("Risk_Precincts_Res2_Loc_Search_BUTTON"))
        self.Level_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 470, 41, 21))
        self.Level_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Res3_Loc_Search_BUTTON"))
        self.Z1_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z1_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 590, 41, 21))
        self.Z1_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z1_Res3_Loc_Search_BUTTON"))
        self.Velocity_Impact_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 710, 41, 21))
        self.Velocity_Impact_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Impact_Res3_Loc_Search_BUTTON"))
        self.HydCat_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.HydCat_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 620, 41, 21))
        self.HydCat_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("HydCat_Res3_Loc_Search_BUTTON"))
        self.Depth_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Depth_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 500, 41, 21))
        self.Depth_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Depth_Res3_Loc_Search_BUTTON"))
        self.Z0_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z0_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 560, 41, 21))
        self.Z0_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z0_Res3_Loc_Search_BUTTON"))
        self.Level_Impact_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 680, 41, 21))
        self.Level_Impact_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Impact_Res3_Loc_Search_BUTTON"))
        self.Velocity_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 530, 41, 21))
        self.Velocity_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Res3_Loc_Search_BUTTON"))
        self.Risk_Precincts_Res3_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res3_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1050, 650, 41, 21))
        self.Risk_Precincts_Res3_Loc_Search_BUTTON.setObjectName(_fromUtf8("Risk_Precincts_Res3_Loc_Search_BUTTON"))
        self.Additional_Res_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Additional_Res_CAPTION.setGeometry(QtCore.QRect(610, 440, 621, 16))
        self.Additional_Res_CAPTION.setObjectName(_fromUtf8("Additional_Res_CAPTION"))
        self.Z1_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z1_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 590, 41, 21))
        self.Z1_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z1_Res4_Loc_Search_BUTTON"))
        self.Z0_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Z0_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 560, 41, 21))
        self.Z0_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Z0_Res4_Loc_Search_BUTTON"))
        self.Depth_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Depth_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 500, 41, 21))
        self.Depth_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Depth_Res4_Loc_Search_BUTTON"))
        self.Level_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 470, 41, 21))
        self.Level_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Res4_Loc_Search_BUTTON"))
        self.Level_Impact_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 680, 41, 21))
        self.Level_Impact_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Level_Impact_Res4_Loc_Search_BUTTON"))
        self.Velocity_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 530, 41, 21))
        self.Velocity_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Res4_Loc_Search_BUTTON"))
        self.HydCat_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.HydCat_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 620, 41, 21))
        self.HydCat_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("HydCat_Res4_Loc_Search_BUTTON"))
        self.Velocity_Impact_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 710, 41, 21))
        self.Velocity_Impact_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Velocity_Impact_Res4_Loc_Search_BUTTON"))
        self.Risk_Precincts_Res4_Loc_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res4_Loc_Search_BUTTON.setGeometry(QtCore.QRect(1400, 650, 41, 21))
        self.Risk_Precincts_Res4_Loc_Search_BUTTON.setObjectName(_fromUtf8("Risk_Precincts_Res4_Loc_Search_BUTTON"))
        self.Appendix_Ref_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Appendix_Ref_CAPTION.setGeometry(QtCore.QRect(120, 440, 111, 16))
        self.Appendix_Ref_CAPTION.setObjectName(_fromUtf8("Appendix_Ref_CAPTION"))
        self.Level_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 470, 111, 21))
        self.Level_Res1_VCP_SELECT.setObjectName(_fromUtf8("Level_Res1_VCP_SELECT"))
        self.Velocity_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 530, 111, 21))
        self.Velocity_Res1_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Res1_VCP_SELECT"))
        self.Z0_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 560, 111, 21))
        self.Z0_Res1_VCP_SELECT.setObjectName(_fromUtf8("Z0_Res1_VCP_SELECT"))
        self.Z1_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 590, 111, 21))
        self.Z1_Res1_VCP_SELECT.setObjectName(_fromUtf8("Z1_Res1_VCP_SELECT"))
        self.HydCat_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 620, 111, 21))
        self.HydCat_Res1_VCP_SELECT.setObjectName(_fromUtf8("HydCat_Res1_VCP_SELECT"))
        self.Level_Impact_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 680, 111, 21))
        self.Level_Impact_Res1_VCP_SELECT.setObjectName(_fromUtf8("Level_Impact_Res1_VCP_SELECT"))
        self.Level_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 470, 111, 21))
        self.Level_Res2_VCP_SELECT.setObjectName(_fromUtf8("Level_Res2_VCP_SELECT"))
        self.Velocity_Impact_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 710, 111, 21))
        self.Velocity_Impact_Res1_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res1_VCP_SELECT"))
        self.Z1_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 590, 111, 21))
        self.Z1_Res2_VCP_SELECT.setObjectName(_fromUtf8("Z1_Res2_VCP_SELECT"))
        self.Depth_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 500, 111, 21))
        self.Depth_Res1_VCP_SELECT.setObjectName(_fromUtf8("Depth_Res1_VCP_SELECT"))
        self.Risk_Precincts_Res1_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res1_VCP_SELECT.setGeometry(QtCore.QRect(400, 650, 111, 21))
        self.Risk_Precincts_Res1_VCP_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res1_VCP_SELECT"))
        self.Z0_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 560, 111, 21))
        self.Z0_Res2_VCP_SELECT.setObjectName(_fromUtf8("Z0_Res2_VCP_SELECT"))
        self.HydCat_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 620, 111, 21))
        self.HydCat_Res2_VCP_SELECT.setObjectName(_fromUtf8("HydCat_Res2_VCP_SELECT"))
        self.Velocity_Impact_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 710, 111, 21))
        self.Velocity_Impact_Res2_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res2_VCP_SELECT"))
        self.Depth_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 500, 111, 21))
        self.Depth_Res3_VCP_SELECT.setObjectName(_fromUtf8("Depth_Res3_VCP_SELECT"))
        self.Velocity_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 530, 111, 21))
        self.Velocity_Res3_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Res3_VCP_SELECT"))
        self.Level_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 470, 111, 21))
        self.Level_Res3_VCP_SELECT.setObjectName(_fromUtf8("Level_Res3_VCP_SELECT"))
        self.Velocity_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 530, 111, 21))
        self.Velocity_Res2_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Res2_VCP_SELECT"))
        self.Depth_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 500, 111, 21))
        self.Depth_Res2_VCP_SELECT.setObjectName(_fromUtf8("Depth_Res2_VCP_SELECT"))
        self.Level_Impact_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 680, 111, 21))
        self.Level_Impact_Res2_VCP_SELECT.setObjectName(_fromUtf8("Level_Impact_Res2_VCP_SELECT"))
        self.Risk_Precincts_Res2_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res2_VCP_SELECT.setGeometry(QtCore.QRect(750, 650, 111, 21))
        self.Risk_Precincts_Res2_VCP_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res2_VCP_SELECT"))
        self.Depth_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 500, 111, 21))
        self.Depth_Res4_VCP_SELECT.setObjectName(_fromUtf8("Depth_Res4_VCP_SELECT"))
        self.Z1_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 590, 111, 21))
        self.Z1_Res3_VCP_SELECT.setObjectName(_fromUtf8("Z1_Res3_VCP_SELECT"))
        self.Z0_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 560, 111, 21))
        self.Z0_Res3_VCP_SELECT.setObjectName(_fromUtf8("Z0_Res3_VCP_SELECT"))
        self.HydCat_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 620, 111, 21))
        self.HydCat_Res4_VCP_SELECT.setObjectName(_fromUtf8("HydCat_Res4_VCP_SELECT"))
        self.Z1_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 590, 111, 21))
        self.Z1_Res4_VCP_SELECT.setObjectName(_fromUtf8("Z1_Res4_VCP_SELECT"))
        self.Velocity_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 530, 111, 21))
        self.Velocity_Res4_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Res4_VCP_SELECT"))
        self.Z0_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 560, 111, 21))
        self.Z0_Res4_VCP_SELECT.setObjectName(_fromUtf8("Z0_Res4_VCP_SELECT"))
        self.Velocity_Impact_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 710, 111, 21))
        self.Velocity_Impact_Res4_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res4_VCP_SELECT"))
        self.Risk_Precincts_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 650, 111, 21))
        self.Risk_Precincts_Res4_VCP_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res4_VCP_SELECT"))
        self.HydCat_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 620, 111, 21))
        self.HydCat_Res3_VCP_SELECT.setObjectName(_fromUtf8("HydCat_Res3_VCP_SELECT"))
        self.Level_Impact_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 680, 111, 21))
        self.Level_Impact_Res3_VCP_SELECT.setObjectName(_fromUtf8("Level_Impact_Res3_VCP_SELECT"))
        self.Risk_Precincts_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 650, 111, 21))
        self.Risk_Precincts_Res3_VCP_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res3_VCP_SELECT"))
        self.Level_Impact_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 680, 111, 21))
        self.Level_Impact_Res4_VCP_SELECT.setObjectName(_fromUtf8("Level_Impact_Res4_VCP_SELECT"))
        self.Velocity_Impact_Res3_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res3_VCP_SELECT.setGeometry(QtCore.QRect(1100, 710, 111, 21))
        self.Velocity_Impact_Res3_VCP_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res3_VCP_SELECT"))
        self.Level_Res4_VCP_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res4_VCP_SELECT.setGeometry(QtCore.QRect(1450, 470, 111, 21))
        self.Level_Res4_VCP_SELECT.setObjectName(_fromUtf8("Level_Res4_VCP_SELECT"))
        self.Q001_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q001_Notation_BOX.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.Q001_Notation_BOX.setObjectName(_fromUtf8("Q001_Notation_BOX"))
        self.Q002_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q002_Notation_BOX.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.Q002_Notation_BOX.setObjectName(_fromUtf8("Q002_Notation_BOX"))
        self.Q005_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q005_Notation_BOX.setGeometry(QtCore.QRect(120, 140, 113, 20))
        self.Q005_Notation_BOX.setObjectName(_fromUtf8("Q005_Notation_BOX"))
        self.Q010_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q010_Notation_BOX.setGeometry(QtCore.QRect(120, 170, 113, 20))
        self.Q010_Notation_BOX.setObjectName(_fromUtf8("Q010_Notation_BOX"))
        self.Q020_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q020_Notation_BOX.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.Q020_Notation_BOX.setObjectName(_fromUtf8("Q020_Notation_BOX"))
        self.Q050_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q050_Notation_BOX.setGeometry(QtCore.QRect(120, 230, 113, 20))
        self.Q050_Notation_BOX.setObjectName(_fromUtf8("Q050_Notation_BOX"))
        self.Q100_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q100_Notation_BOX.setGeometry(QtCore.QRect(120, 260, 113, 20))
        self.Q100_Notation_BOX.setObjectName(_fromUtf8("Q100_Notation_BOX"))
        self.Q200_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q200_Notation_BOX.setGeometry(QtCore.QRect(120, 290, 113, 20))
        self.Q200_Notation_BOX.setObjectName(_fromUtf8("Q200_Notation_BOX"))
        self.Q500_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q500_Notation_BOX.setGeometry(QtCore.QRect(120, 320, 113, 20))
        self.Q500_Notation_BOX.setObjectName(_fromUtf8("Q500_Notation_BOX"))
        self.Q2000_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q2000_Notation_BOX.setGeometry(QtCore.QRect(120, 380, 113, 20))
        self.Q2000_Notation_BOX.setObjectName(_fromUtf8("Q2000_Notation_BOX"))
        self.Q1000_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Q1000_Notation_BOX.setGeometry(QtCore.QRect(120, 350, 113, 20))
        self.Q1000_Notation_BOX.setObjectName(_fromUtf8("Q1000_Notation_BOX"))
        self.QPMF_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.QPMF_Notation_BOX.setGeometry(QtCore.QRect(120, 410, 113, 20))
        self.QPMF_Notation_BOX.setObjectName(_fromUtf8("QPMF_Notation_BOX"))
        self.Level_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 470, 113, 20))
        self.Level_Appendix_Label_BOX.setObjectName(_fromUtf8("Level_Appendix_Label_BOX"))
        self.Depth_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Depth_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 500, 113, 20))
        self.Depth_Appendix_Label_BOX.setObjectName(_fromUtf8("Depth_Appendix_Label_BOX"))
        self.Velocity_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 530, 113, 20))
        self.Velocity_Appendix_Label_BOX.setObjectName(_fromUtf8("Velocity_Appendix_Label_BOX"))
        self.Z0_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z0_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 560, 113, 20))
        self.Z0_Appendix_Label_BOX.setObjectName(_fromUtf8("Z0_Appendix_Label_BOX"))
        self.Z1_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z1_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 590, 113, 20))
        self.Z1_Appendix_Label_BOX.setObjectName(_fromUtf8("Z1_Appendix_Label_BOX"))
        self.HydCat_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.HydCat_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 620, 113, 20))
        self.HydCat_Appendix_Label_BOX.setObjectName(_fromUtf8("HydCat_Appendix_Label_BOX"))
        self.Risk_Precincts_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 650, 113, 20))
        self.Risk_Precincts_Appendix_Label_BOX.setObjectName(_fromUtf8("Risk_Precincts_Appendix_Label_BOX"))
        self.Level_Impact_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Impact_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 680, 113, 20))
        self.Level_Impact_Appendix_Label_BOX.setObjectName(_fromUtf8("Level_Impact_Appendix_Label_BOX"))
        self.Velocity_Impact_Appendix_Label_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Appendix_Label_BOX.setGeometry(QtCore.QRect(120, 710, 113, 20))
        self.Velocity_Impact_Appendix_Label_BOX.setObjectName(_fromUtf8("Velocity_Impact_Appendix_Label_BOX"))
        self.Velocity_Impact_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 710, 113, 20))
        self.Velocity_Impact_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Impact_Res1_Loc_Search_BOX"))
        self.Level_Impact_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 680, 113, 20))
        self.Level_Impact_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Impact_Res1_Loc_Search_BOX"))
        self.Risk_Precincts_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 650, 113, 20))
        self.Risk_Precincts_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Risk_Precincts_Res1_Loc_Search_BOX"))
        self.HydCat_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.HydCat_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 620, 113, 20))
        self.HydCat_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("HydCat_Res1_Loc_Search_BOX"))
        self.Z1_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z1_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 590, 113, 20))
        self.Z1_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Z1_Res1_Loc_Search_BOX"))
        self.Z0_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z0_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 560, 113, 20))
        self.Z0_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Z0_Res1_Loc_Search_BOX"))
        self.Velocity_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 530, 113, 20))
        self.Velocity_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Res1_Loc_Search_BOX"))
        self.Depth_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Depth_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 500, 113, 20))
        self.Depth_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Depth_Res1_Loc_Search_BOX"))
        self.Level_Res1_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Res1_Loc_Search_BOX.setGeometry(QtCore.QRect(240, 470, 113, 20))
        self.Level_Res1_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Res1_Loc_Search_BOX"))
        self.Control_Ref_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Control_Ref_Search_BOX.setGeometry(QtCore.QRect(20, 20, 291, 21))
        self.Control_Ref_Search_BOX.setObjectName(_fromUtf8("Control_Ref_Search_BOX"))
        self.Scenario_1_Title_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_1_Title_BOX.setGeometry(QtCore.QRect(800, 110, 191, 20))
        self.Scenario_1_Title_BOX.setObjectName(_fromUtf8("Scenario_1_Title_BOX"))
        self.Scenario_2_Title_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_2_Title_BOX.setGeometry(QtCore.QRect(800, 140, 191, 20))
        self.Scenario_2_Title_BOX.setObjectName(_fromUtf8("Scenario_2_Title_BOX"))
        self.Scenario_3_Title_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_3_Title_BOX.setGeometry(QtCore.QRect(800, 170, 191, 20))
        self.Scenario_3_Title_BOX.setObjectName(_fromUtf8("Scenario_3_Title_BOX"))
        self.Scenario_4_Title_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_4_Title_BOX.setGeometry(QtCore.QRect(800, 200, 191, 20))
        self.Scenario_4_Title_BOX.setObjectName(_fromUtf8("Scenario_4_Title_BOX"))
        self.Scenario_2_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_2_Notation_BOX.setGeometry(QtCore.QRect(1000, 140, 113, 20))
        self.Scenario_2_Notation_BOX.setObjectName(_fromUtf8("Scenario_2_Notation_BOX"))
        self.Scenario_3_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_3_Notation_BOX.setGeometry(QtCore.QRect(1000, 170, 113, 20))
        self.Scenario_3_Notation_BOX.setObjectName(_fromUtf8("Scenario_3_Notation_BOX"))
        self.Scenario_1_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_1_Notation_BOX.setGeometry(QtCore.QRect(1000, 110, 113, 20))
        self.Scenario_1_Notation_BOX.setObjectName(_fromUtf8("Scenario_1_Notation_BOX"))
        self.Scenario_4_Notation_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Scenario_4_Notation_BOX.setGeometry(QtCore.QRect(1000, 200, 113, 20))
        self.Scenario_4_Notation_BOX.setObjectName(_fromUtf8("Scenario_4_Notation_BOX"))
        self.Centroid_X_Coord_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Centroid_X_Coord_BOX.setGeometry(QtCore.QRect(800, 290, 113, 20))
        self.Centroid_X_Coord_BOX.setObjectName(_fromUtf8("Centroid_X_Coord_BOX"))
        self.Centroid_Y_Coord_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Centroid_Y_Coord_BOX.setGeometry(QtCore.QRect(950, 290, 113, 20))
        self.Centroid_Y_Coord_BOX.setObjectName(_fromUtf8("Centroid_Y_Coord_BOX"))
        self.Zoom_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Zoom_BOX.setGeometry(QtCore.QRect(800, 340, 261, 20))
        self.Zoom_BOX.setObjectName(_fromUtf8("Zoom_BOX"))
        self.Velocity_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 530, 113, 20))
        self.Velocity_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Res2_Loc_Search_BOX"))
        self.Level_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 470, 113, 20))
        self.Level_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Res2_Loc_Search_BOX"))
        self.Z1_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z1_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 590, 113, 20))
        self.Z1_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Z1_Res2_Loc_Search_BOX"))
        self.Level_Impact_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 680, 113, 20))
        self.Level_Impact_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Impact_Res2_Loc_Search_BOX"))
        self.Z0_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z0_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 560, 113, 20))
        self.Z0_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Z0_Res2_Loc_Search_BOX"))
        self.Velocity_Impact_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 710, 113, 20))
        self.Velocity_Impact_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Impact_Res2_Loc_Search_BOX"))
        self.Risk_Precincts_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 650, 113, 20))
        self.Risk_Precincts_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Risk_Precincts_Res2_Loc_Search_BOX"))
        self.Depth_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Depth_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 500, 113, 20))
        self.Depth_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("Depth_Res2_Loc_Search_BOX"))
        self.HydCat_Res2_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.HydCat_Res2_Loc_Search_BOX.setGeometry(QtCore.QRect(590, 620, 113, 20))
        self.HydCat_Res2_Loc_Search_BOX.setObjectName(_fromUtf8("HydCat_Res2_Loc_Search_BOX"))
        self.Z0_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z0_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 560, 113, 20))
        self.Z0_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Z0_Res3_Loc_Search_BOX"))
        self.Depth_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Depth_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 500, 113, 20))
        self.Depth_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Depth_Res3_Loc_Search_BOX"))
        self.Velocity_Impact_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 710, 113, 20))
        self.Velocity_Impact_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Impact_Res3_Loc_Search_BOX"))
        self.Z1_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z1_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 590, 113, 20))
        self.Z1_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Z1_Res3_Loc_Search_BOX"))
        self.Velocity_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 530, 113, 20))
        self.Velocity_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Res3_Loc_Search_BOX"))
        self.Risk_Precincts_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 650, 113, 20))
        self.Risk_Precincts_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Risk_Precincts_Res3_Loc_Search_BOX"))
        self.Level_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 470, 113, 20))
        self.Level_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Res3_Loc_Search_BOX"))
        self.Level_Impact_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 680, 113, 20))
        self.Level_Impact_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Impact_Res3_Loc_Search_BOX"))
        self.HydCat_Res3_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.HydCat_Res3_Loc_Search_BOX.setGeometry(QtCore.QRect(940, 620, 113, 20))
        self.HydCat_Res3_Loc_Search_BOX.setObjectName(_fromUtf8("HydCat_Res3_Loc_Search_BOX"))
        self.Level_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 470, 113, 20))
        self.Level_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Res4_Loc_Search_BOX"))
        self.Level_Impact_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 680, 113, 20))
        self.Level_Impact_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Level_Impact_Res4_Loc_Search_BOX"))
        self.Depth_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Depth_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 500, 113, 20))
        self.Depth_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Depth_Res4_Loc_Search_BOX"))
        self.HydCat_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.HydCat_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 620, 113, 20))
        self.HydCat_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("HydCat_Res4_Loc_Search_BOX"))
        self.Velocity_Impact_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 710, 113, 20))
        self.Velocity_Impact_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Impact_Res4_Loc_Search_BOX"))
        self.Velocity_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Velocity_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 530, 113, 20))
        self.Velocity_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Velocity_Res4_Loc_Search_BOX"))
        self.Z0_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z0_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 560, 113, 20))
        self.Z0_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Z0_Res4_Loc_Search_BOX"))
        self.Z1_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Z1_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 590, 113, 20))
        self.Z1_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Z1_Res4_Loc_Search_BOX"))
        self.Risk_Precincts_Res4_Loc_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res4_Loc_Search_BOX.setGeometry(QtCore.QRect(1290, 650, 113, 20))
        self.Risk_Precincts_Res4_Loc_Search_BOX.setObjectName(_fromUtf8("Risk_Precincts_Res4_Loc_Search_BOX"))
        self.Style_Control_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Style_Control_CAPTION.setGeometry(QtCore.QRect(390, 0, 311, 16))
        self.Style_Control_CAPTION.setObjectName(_fromUtf8("Style_Control_CAPTION"))
        self.Style_Dir_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Style_Dir_Search_BUTTON.setGeometry(QtCore.QRect(680, 20, 51, 21))
        self.Style_Dir_Search_BUTTON.setObjectName(_fromUtf8("Style_Dir_Search_BUTTON"))
        self.Load_Style_Dir_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Load_Style_Dir_BUTTON.setGeometry(QtCore.QRect(730, 20, 51, 21))
        self.Load_Style_Dir_BUTTON.setObjectName(_fromUtf8("Load_Style_Dir_BUTTON"))
        self.Style_Dir_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Style_Dir_Search_BOX.setGeometry(QtCore.QRect(390, 20, 291, 21))
        self.Style_Dir_Search_BOX.setObjectName(_fromUtf8("Style_Dir_Search_BOX"))
        self.CRS_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.CRS_Search_BUTTON.setGeometry(QtCore.QRect(1090, 20, 51, 21))
        self.CRS_Search_BUTTON.setObjectName(_fromUtf8("CRS_Search_BUTTON"))
        self.CRS_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.CRS_Search_BOX.setGeometry(QtCore.QRect(800, 20, 291, 21))
        self.CRS_Search_BOX.setObjectName(_fromUtf8("CRS_Search_BOX"))
        self.CRS_Caption = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.CRS_Caption.setGeometry(QtCore.QRect(800, 0, 411, 16))
        self.CRS_Caption.setObjectName(_fromUtf8("CRS_Caption"))
        self.Legend_Entry_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Legend_Entry_CAPTION.setGeometry(QtCore.QRect(390, 320, 281, 16))
        self.Legend_Entry_CAPTION.setObjectName(_fromUtf8("Legend_Entry_CAPTION"))
        self.Shift_up_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Shift_up_BUTTON.setGeometry(QtCore.QRect(620, 240, 31, 23))
        self.Shift_up_BUTTON.setObjectName(_fromUtf8("Shift_up_BUTTON"))
        self.Add_Layer_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Add_Layer_BUTTON.setGeometry(QtCore.QRect(390, 240, 81, 23))
        self.Add_Layer_BUTTON.setObjectName(_fromUtf8("Add_Layer_BUTTON"))
        self.Style_Select_COMBO = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Style_Select_COMBO.setGeometry(QtCore.QRect(390, 390, 311, 22))
        self.Style_Select_COMBO.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Style_Select_COMBO.setObjectName(_fromUtf8("Style_Select_COMBO"))
        self.Layer_Loc_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Layer_Loc_CAPTION.setGeometry(QtCore.QRect(390, 270, 281, 16))
        self.Layer_Loc_CAPTION.setObjectName(_fromUtf8("Layer_Loc_CAPTION"))
        self.Remove_Layer_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Remove_Layer_BUTTON.setGeometry(QtCore.QRect(480, 240, 81, 23))
        self.Remove_Layer_BUTTON.setObjectName(_fromUtf8("Remove_Layer_BUTTON"))
        self.VCP_Selection_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.VCP_Selection_CAPTION.setGeometry(QtCore.QRect(390, 370, 281, 16))
        self.VCP_Selection_CAPTION.setObjectName(_fromUtf8("VCP_Selection_CAPTION"))
        self.Shift_Down_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Shift_Down_BUTTON.setGeometry(QtCore.QRect(660, 240, 41, 23))
        self.Shift_Down_BUTTON.setObjectName(_fromUtf8("Shift_Down_BUTTON"))
        self.Layer_Search_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Layer_Search_BOX.setGeometry(QtCore.QRect(390, 290, 261, 21))
        self.Layer_Search_BOX.setObjectName(_fromUtf8("Layer_Search_BOX"))
        self.Layer_Search_BUTTON = QtGui.QPushButton(Ui_New_ProjectDialogBase)
        self.Layer_Search_BUTTON.setGeometry(QtCore.QRect(650, 290, 51, 21))
        self.Layer_Search_BUTTON.setObjectName(_fromUtf8("Layer_Search_BUTTON"))
        self.Legend_Entry_BOX = QtGui.QLineEdit(Ui_New_ProjectDialogBase)
        self.Legend_Entry_BOX.setGeometry(QtCore.QRect(390, 340, 311, 21))
        self.Legend_Entry_BOX.setObjectName(_fromUtf8("Legend_Entry_BOX"))
        self.Layer_List_TABLE = QtGui.QTableWidget(Ui_New_ProjectDialogBase)
        self.Layer_List_TABLE.setGeometry(QtCore.QRect(390, 60, 311, 171))
        self.Layer_List_TABLE.setObjectName(_fromUtf8("Layer_List_TABLE"))
        self.Layer_List_TABLE.setColumnCount(3)
        self.Layer_List_TABLE.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.Layer_List_TABLE.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Layer_List_TABLE.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Layer_List_TABLE.setHorizontalHeaderItem(2, item)
        self.Risk_Precincts_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 650, 51, 21))
        self.Risk_Precincts_Res1_Format_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res1_Format_SELECT"))
        self.Risk_Precincts_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 500, 51, 21))
        self.Depth_Res1_Format_SELECT.setObjectName(_fromUtf8("Depth_Res1_Format_SELECT"))
        self.Depth_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 710, 51, 21))
        self.Velocity_Impact_Res1_Format_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res1_Format_SELECT"))
        self.Velocity_Impact_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 560, 51, 21))
        self.Z0_Res1_Format_SELECT.setObjectName(_fromUtf8("Z0_Res1_Format_SELECT"))
        self.Z0_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res1_VCP_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res1_VCP_Format_SELECT.setGeometry(QtCore.QRect(520, 590, 51, 21))
        self.Z1_Res1_VCP_Format_SELECT.setObjectName(_fromUtf8("Z1_Res1_VCP_Format_SELECT"))
        self.Z1_Res1_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res1_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res1_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Res1_Format_CAPTION = QtGui.QLabel(Ui_New_ProjectDialogBase)
        self.Res1_Format_CAPTION.setGeometry(QtCore.QRect(520, 440, 101, 16))
        self.Res1_Format_CAPTION.setObjectName(_fromUtf8("Res1_Format_CAPTION"))
        self.Level_Impact_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 680, 51, 21))
        self.Level_Impact_Res1_Format_SELECT.setObjectName(_fromUtf8("Level_Impact_Res1_Format_SELECT"))
        self.Level_Impact_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 530, 51, 21))
        self.Velocity_Res1_Format_SELECT.setObjectName(_fromUtf8("Velocity_Res1_Format_SELECT"))
        self.Velocity_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 620, 51, 21))
        self.HydCat_Res1_Format_SELECT.setObjectName(_fromUtf8("HydCat_Res1_Format_SELECT"))
        self.HydCat_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res1_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res1_Format_SELECT.setGeometry(QtCore.QRect(520, 470, 51, 21))
        self.Level_Res1_Format_SELECT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Level_Res1_Format_SELECT.setObjectName(_fromUtf8("Level_Res1_Format_SELECT"))
        self.Level_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res1_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 560, 51, 21))
        self.Z0_Res2_Format_SELECT.setObjectName(_fromUtf8("Z0_Res2_Format_SELECT"))
        self.Z0_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 710, 51, 21))
        self.Velocity_Impact_Res2_Format_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res2_Format_SELECT"))
        self.Velocity_Impact_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 470, 51, 21))
        self.Level_Res2_Format_SELECT.setObjectName(_fromUtf8("Level_Res2_Format_SELECT"))
        self.Level_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 650, 51, 21))
        self.Risk_Precincts_Res2_Format_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res2_Format_SELECT"))
        self.Risk_Precincts_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 620, 51, 21))
        self.HydCat_Res2_Format_SELECT.setObjectName(_fromUtf8("HydCat_Res2_Format_SELECT"))
        self.HydCat_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res2_VCP_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res2_VCP_Format_SELECT.setGeometry(QtCore.QRect(870, 590, 51, 21))
        self.Z1_Res2_VCP_Format_SELECT.setObjectName(_fromUtf8("Z1_Res2_VCP_Format_SELECT"))
        self.Z1_Res2_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res2_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res2_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 500, 51, 21))
        self.Depth_Res2_Format_SELECT.setObjectName(_fromUtf8("Depth_Res2_Format_SELECT"))
        self.Depth_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 530, 51, 21))
        self.Velocity_Res2_Format_SELECT.setObjectName(_fromUtf8("Velocity_Res2_Format_SELECT"))
        self.Velocity_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res2_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res2_Format_SELECT.setGeometry(QtCore.QRect(870, 680, 51, 21))
        self.Level_Impact_Res2_Format_SELECT.setObjectName(_fromUtf8("Level_Impact_Res2_Format_SELECT"))
        self.Level_Impact_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res2_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 500, 51, 21))
        self.Depth_Res3_Format_SELECT.setObjectName(_fromUtf8("Depth_Res3_Format_SELECT"))
        self.Depth_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 680, 51, 21))
        self.Level_Impact_Res3_Format_SELECT.setObjectName(_fromUtf8("Level_Impact_Res3_Format_SELECT"))
        self.Level_Impact_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 530, 51, 21))
        self.Velocity_Res3_Format_SELECT.setObjectName(_fromUtf8("Velocity_Res3_Format_SELECT"))
        self.Velocity_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 650, 51, 21))
        self.Risk_Precincts_Res3_Format_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res3_Format_SELECT"))
        self.Risk_Precincts_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 710, 51, 21))
        self.Velocity_Impact_Res3_Format_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res3_Format_SELECT"))
        self.Velocity_Impact_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 620, 51, 21))
        self.HydCat_Res3_Format_SELECT.setObjectName(_fromUtf8("HydCat_Res3_Format_SELECT"))
        self.HydCat_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res3_VCP_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res3_VCP_Format_SELECT.setGeometry(QtCore.QRect(1220, 590, 51, 21))
        self.Z1_Res3_VCP_Format_SELECT.setObjectName(_fromUtf8("Z1_Res3_VCP_Format_SELECT"))
        self.Z1_Res3_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res3_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res3_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 560, 51, 21))
        self.Z0_Res3_Format_SELECT.setObjectName(_fromUtf8("Z0_Res3_Format_SELECT"))
        self.Z0_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res3_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res3_Format_SELECT.setGeometry(QtCore.QRect(1220, 470, 51, 21))
        self.Level_Res3_Format_SELECT.setObjectName(_fromUtf8("Level_Res3_Format_SELECT"))
        self.Level_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res3_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Depth_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 500, 51, 21))
        self.Depth_Res4_Format_SELECT.setObjectName(_fromUtf8("Depth_Res4_Format_SELECT"))
        self.Depth_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Depth_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Impact_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 680, 51, 21))
        self.Level_Impact_Res4_Format_SELECT.setObjectName(_fromUtf8("Level_Impact_Res4_Format_SELECT"))
        self.Level_Impact_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Impact_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 530, 51, 21))
        self.Velocity_Res4_Format_SELECT.setObjectName(_fromUtf8("Velocity_Res4_Format_SELECT"))
        self.Velocity_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Risk_Precincts_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 650, 51, 21))
        self.Risk_Precincts_Res4_Format_SELECT.setObjectName(_fromUtf8("Risk_Precincts_Res4_Format_SELECT"))
        self.Risk_Precincts_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Risk_Precincts_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Velocity_Impact_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 710, 51, 21))
        self.Velocity_Impact_Res4_Format_SELECT.setObjectName(_fromUtf8("Velocity_Impact_Res4_Format_SELECT"))
        self.Velocity_Impact_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Velocity_Impact_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.HydCat_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 620, 51, 21))
        self.HydCat_Res4_Format_SELECT.setObjectName(_fromUtf8("HydCat_Res4_Format_SELECT"))
        self.HydCat_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.HydCat_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res4_VCP_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z1_Res4_VCP_Format_SELECT.setGeometry(QtCore.QRect(1570, 590, 51, 21))
        self.Z1_Res4_VCP_Format_SELECT.setObjectName(_fromUtf8("Z1_Res4_VCP_Format_SELECT"))
        self.Z1_Res4_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res4_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z1_Res4_VCP_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Z0_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 560, 51, 21))
        self.Z0_Res4_Format_SELECT.setObjectName(_fromUtf8("Z0_Res4_Format_SELECT"))
        self.Z0_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Z0_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res4_Format_SELECT = QtGui.QComboBox(Ui_New_ProjectDialogBase)
        self.Level_Res4_Format_SELECT.setGeometry(QtCore.QRect(1570, 470, 51, 21))
        self.Level_Res4_Format_SELECT.setObjectName(_fromUtf8("Level_Res4_Format_SELECT"))
        self.Level_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res4_Format_SELECT.addItem(_fromUtf8(""))
        self.Level_Res4_Format_SELECT.addItem(_fromUtf8(""))

        self.retranslateUi(Ui_New_ProjectDialogBase)
        QtCore.QObject.connect(self.Master_Buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), Ui_New_ProjectDialogBase.accept)
        QtCore.QObject.connect(self.Master_Buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), Ui_New_ProjectDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(Ui_New_ProjectDialogBase)

    def retranslateUi(self, Ui_New_ProjectDialogBase):
        Ui_New_ProjectDialogBase.setWindowTitle(_translate("Ui_New_ProjectDialogBase", "Figure_Builder", None))
        self.Figure_list_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Event List", None))
        self.Layer_List_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Layer List", None))
        self.Figure_Control_Path_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Figure Control File (Figures will be produced in the same folder location)", None))
        self.Control_Ref_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Figure_Zoom_Centroid_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Set Figure Area", None))
        self.Centroid_X_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Centroid X-Coordinate", None))
        self.Centroid_Y_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Centroid Y-Coordinate", None))
        self.Zoom_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Figure Zoom/Scale (e.g 1000 for 1cm:1000m)", None))
        self.Populate_View_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Populate Using Current View", None))
        self.Q001_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "1 Year ARI", None))
        self.Q005_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "5 Year ARI", None))
        self.Q002_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "2 Year ARI", None))
        self.Q010_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "10 Year ARI", None))
        self.Q100_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "100 Year ARI", None))
        self.Q200_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "200 Year ARI", None))
        self.Q020_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "20 Year ARI", None))
        self.Q050_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "50 Year ARI", None))
        self.Q2000_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "2000 Year ARI", None))
        self.QPMF_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "PMF", None))
        self.Q500_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "500 Year ARI", None))
        self.Q1000_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "1000 Year ARI", None))
        self.Event_Notation_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Event Notation", None))
        self.Mapping_Results_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Mapping Results", None))
        self.Res1_Location_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Result Location", None))
        self.Velocity_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Velocity", None))
        self.Z0_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Z0", None))
        self.HydCat_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Hydraulic Cat", None))
        self.Level_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Level", None))
        self.Depth_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Depth", None))
        self.Risk_Precincts_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Risk Precints", None))
        self.Z1_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Z1", None))
        self.Res1_VCP_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Result Style", None))
        self.Level_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Depth_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z0_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z1_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Risk_Precincts_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.HydCat_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Scenario_Notation_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Result Scenario Notation(e.g DEV)", None))
        self.Scenario_Title_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Scenario Title (as seen in Figure Title)", None))
        self.Layout_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", "A4 Portrait", None))
        self.Layout_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", "A4 Landscape", None))
        self.Layout_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", "A3 Portrait", None))
        self.Layout_SELECT.setItemText(3, _translate("Ui_New_ProjectDialogBase", "A3 Landscape", None))
        self.Page_Layout_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Page Layout", None))
        self.Level_Impact_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Impacts_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Level Impacts", None))
        self.Velocity_Impacts_CHECK.setText(_translate("Ui_New_ProjectDialogBase", "Velocity Impacts", None))
        self.Velocity_Impact_Res1_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z1_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Impact_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.HydCat_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Depth_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z0_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Impact_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Risk_Precincts_Res2_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z1_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Impact_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.HydCat_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Depth_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z0_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Impact_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Risk_Precincts_Res3_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Additional_Res_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Additional Result Locations for aids such as Contours or Vector Arrows (must have matching Event and Scenario notation)", None))
        self.Z1_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Z0_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Depth_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Level_Impact_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.HydCat_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Velocity_Impact_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Risk_Precincts_Res4_Loc_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Appendix_Ref_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Appendix Referance", None))
        self.Style_Control_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Style Control Directory", None))
        self.Style_Dir_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.Load_Style_Dir_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Load", None))
        self.CRS_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        self.CRS_Caption.setText(_translate("Ui_New_ProjectDialogBase", "Set Project CRS", None))
        self.Legend_Entry_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Legend Entry", None))
        self.Shift_up_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "UP", None))
        self.Add_Layer_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Add Layer", None))
        self.Layer_Loc_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Layer Location", None))
        self.Remove_Layer_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Remove Layer", None))
        self.VCP_Selection_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Colour Profile (Define Category Legend Entires in Style)", None))
        self.Shift_Down_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "DOWN", None))
        self.Layer_Search_BUTTON.setText(_translate("Ui_New_ProjectDialogBase", "Search", None))
        item = self.Layer_List_TABLE.horizontalHeaderItem(0)
        item.setText(_translate("Ui_New_ProjectDialogBase", "Location", None))
        item = self.Layer_List_TABLE.horizontalHeaderItem(1)
        item.setText(_translate("Ui_New_ProjectDialogBase", "Colour", None))
        item = self.Layer_List_TABLE.horizontalHeaderItem(2)
        item.setText(_translate("Ui_New_ProjectDialogBase", "Legend Entry", None))
        self.Risk_Precincts_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Risk_Precincts_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Risk_Precincts_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Depth_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Depth_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Depth_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Impact_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Impact_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Impact_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z0_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z0_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z0_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z1_Res1_VCP_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z1_Res1_VCP_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z1_Res1_VCP_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Res1_Format_CAPTION.setText(_translate("Ui_New_ProjectDialogBase", "Result Format", None))
        self.Level_Impact_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Impact_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Impact_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.HydCat_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.HydCat_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.HydCat_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Res1_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Res1_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Res1_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z0_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z0_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z0_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Impact_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Impact_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Impact_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Risk_Precincts_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Risk_Precincts_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Risk_Precincts_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.HydCat_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.HydCat_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.HydCat_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z1_Res2_VCP_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z1_Res2_VCP_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z1_Res2_VCP_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Depth_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Depth_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Depth_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Impact_Res2_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Impact_Res2_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Impact_Res2_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Depth_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Depth_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Depth_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Impact_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Impact_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Impact_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Risk_Precincts_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Risk_Precincts_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Risk_Precincts_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Impact_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Impact_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Impact_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.HydCat_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.HydCat_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.HydCat_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z1_Res3_VCP_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z1_Res3_VCP_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z1_Res3_VCP_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z0_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z0_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z0_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Res3_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Res3_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Res3_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Depth_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Depth_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Depth_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Impact_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Impact_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Impact_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Risk_Precincts_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Risk_Precincts_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Risk_Precincts_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Velocity_Impact_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Velocity_Impact_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Velocity_Impact_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.HydCat_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.HydCat_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.HydCat_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z1_Res4_VCP_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z1_Res4_VCP_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z1_Res4_VCP_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Z0_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Z0_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Z0_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))
        self.Level_Res4_Format_SELECT.setItemText(0, _translate("Ui_New_ProjectDialogBase", ".tab", None))
        self.Level_Res4_Format_SELECT.setItemText(1, _translate("Ui_New_ProjectDialogBase", ".shp", None))
        self.Level_Res4_Format_SELECT.setItemText(2, _translate("Ui_New_ProjectDialogBase", ".asc", None))

